pipeline {
    agent { label 'docker-agent' }

    environment {
        GITHUB_REPO = "https://github.com/jhonuel/dev02.git"
        GIT_BRANCH = "dev02"
        DOCKER_CREDENTIALS_ID = "docker-hub-credentials" // Reemplaza con el ID de tus credenciales en Jenkins
        DOCKER_IMAGE = "jhonuel/payment-gateway-prod"
        DOCKER_TAG = "latest"
    }

    stages {
        stage('Clone Repository') {
            steps {
                echo 'Clonando el repositorio...'
                sh 'git --version' // Verificar si git está instalado
                sh 'rm -rf dev02 || true' // Asegurar que no existe un directorio previo
                sh 'git clone ${GITHUB_REPO} -b ${GIT_BRANCH}'
            }
        }

        stage('Build') {
            steps {
                echo 'Compilando el proyecto...'
                sh 'cd dev02 && mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                echo 'Ejecutando pruebas...'
                sh 'cd dev02 && mvn test'
            }
        }

        stage('Docker Build and Push') {
            steps {
                echo 'Construyendo la imagen Docker...'
                script {
                    docker.withRegistry('', "${DOCKER_CREDENTIALS_ID}") {
                        sh 'cd dev02 && docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .'
                        sh 'docker push ${DOCKER_IMAGE}:${DOCKER_TAG}'
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Desplegando la aplicación...'
                // Detener y eliminar contenedores existentes
                sh 'docker-compose down -v'
                // Construir y levantar los nuevos contenedores
                sh 'docker-compose up -d --build'
            }
        }
    }

    post {
        always {
            echo 'Pipeline finalizado.'
        }
        success {
            echo 'Pipeline completado con éxito.'
        }
        failure {
            echo 'Pipeline fallido.'
        }
    }
}
